use_frameworks!

target 'AISphereView_Example' do
    pod 'AISphereView', :path => '../'
    pod 'Reveal-SDK', '~> 11', :configurations => ['Debug']
    
    target 'AISphereView_Tests' do
        inherit! :search_paths
        
        
    end
end
